package inc.roms.rcs.vo.issue;

public enum IssueReason {
    COULDNT_PICK,
    NO_EMPTY_TOTES,
    DISPOSE_REQUESTED,
    UNKNOWN_SKU,
    UNKNOWN_TOTE,
    OUT_OF_STOCK,
    CANNOT_DELIVER,
    ORDER_NOT_FOUND,
    ORDER_ALREADY_DELIVERED,
    CANNOT_PICK,
    NO_SPACE_FOR_STOCK,
    NO_SPACE_FOR_TOTE,
    COULDNT_CONNECT_TO_MHE,
    ORDER_NOT_COLLECTED,
    ORDER_TO_BIG,
    COULDNT_PLACE,
    OMNICHANNEL_NOT_RESPONDING,
    UNKNOWN_GATE,
    NO_READ,
    TOTE_PROBLEM,
    ORDER_ALREADY_EXISTS
}
