package inc.roms.rcs.vo.issue;

public enum IssueAction {
    CHECK_SKU_BATCH,
    DISPOSE_SKU,
    CHECK_SKU,
    DISPOSE_ORDERS,
    DISPOSE_STOCK,
    CHECK_TOTE,
    CHECK_PREORDER,
    EMPTY_TOTES,
    CHECK_ORDER,
    CLEAN_ZONE,
    VERIFY_MHE_OPERATOR,
    VERIFY_ORDERS_CONSTRAINTS,
    CHECK_OMNICHANNEL,
    CHECK_TOTE_BARCODES,
    REMOVE_OVERFILL,
    REINDUCT_TOTE,
    UNKNOWN
}
