package inc.roms.rcs.api.error.model;

public enum RcsErrorCode {

    SYSTEM_EXCEPTION,
    MHE_EXCEPTION,
    OMNI_CHANNEL_UNAVAILABLE,
    UNAUTHORIZED,
    METHOD_NOT_ALLOWED,
    MEDIA_TYPE_NOT_SUPPORTED,
    REQUEST_NOT_VALID,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    NO_SPACE_FOR_TOTE, RESOURCE_NOT_AVAILABLE

}
